site_name: Trabalho Spark EngDados - SATC
site_url: https://viniciusmilanez.github.io/trabalho-spark-engdados/
repo_url: https://github.com/viniciusmilanez/trabalho-spark-engdados

theme:
  name: material
  palette:
    primary: indigo
    accent: cyan
  features:
    - content.code.copy

nav:
  - 🏠 Home: index.md
  - ⚡ Apache Spark: spark.md
  - 🏔️ Delta Lake: delta.md
  - 🧊 Apache Iceberg: iceberg.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format